# Generated by Django 3.1.3 on 2021-04-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackConfiguration',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('attack_choice', models.CharField(choices=[('no-attack', 'No Attack'), ('ucl', 'User Code Leak'), ('dcl', 'Device Code Leak'), ('mitm', 'Man in the Middle'), ('rp', 'Remote Phishing'), ('csrfqr', 'CSRF with QR-Code'), ('cdc', 'Corrupted Device Client'), ('dos', 'Denial of Service')], default='no-attack', max_length=10)),
                ('ucl_choice', models.CharField(choices=[('prox', 'Attacker in spatial proximity'), ('sep', 'Attacker not in spatial proximity (using Referer Header)'), ('bf', 'Brute Force'), ('', '')], default='', max_length=4)),
                ('dcl_choice', models.CharField(choices=[('prox', 'Attacker in spatial proximity'), ('sep', 'Attacker not in spatial proximity (using Referer Header)'), ('bf', 'Brute Force'), ('', '')], default='', max_length=4)),
                ('mitm_choice', models.CharField(choices=[('with_token_response', 'Attacker forwards the device access token         response from the AS to the device'), ('', '')], default='', max_length=20)),
                ('cdc_choice', models.CharField(choices=[('with_authentication', 'Attacker completes Device Flow'), ('', '')], default='', max_length=25)),
                ('rp_choice', models.CharField(choices=[('direct', 'Link in Email is verification_uri_complete'), ('indirect', "Link in Email redirects to Eve's server to obtain a new         user_code")], default='', max_length=25)),
                ('show_device_name', models.BooleanField(default=False)),
                ('show_scope', models.BooleanField(default=False)),
                ('interval', models.IntegerField(default=1)),
                ('timeout', models.IntegerField(default=30)),
                ('user_code_entropy', models.IntegerField(default=20)),
                ('max_rate_login', models.IntegerField(default=3)),
                ('rate_limiting_ucl', models.BooleanField(default=False)),
                ('device_code_entropy', models.IntegerField(default=20)),
                ('max_rate_polling', models.IntegerField(default=3)),
                ('rate_limiting_dcl', models.BooleanField(default=False)),
                ('number_of_devices', models.IntegerField(default=20)),
                ('max_rate_dos', models.FloatField(default=2.5)),
            ],
        ),
    ]
